"""empty message

Revision ID: 677ed3df97c2
Revises: cbe8a309fd66
Create Date: 2023-01-13 20:46:38.400160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677ed3df97c2'
down_revision = 'cbe8a309fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_type', sa.Enum('draft', 'show', name='postpublishtype'), server_default='show', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('has_type')

    # ### end Alembic commands ###
